name: Geranium Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Install dependencies
      run: |
        brew install ldid xz git
        brew install --cask macfuse

    - name: Install Theos (修正版)
      run: |
        git clone --recursive https://github.com/theos/theos.git $THEOS
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export THEOS=$THEOS" >> $GITHUB_ENV
        echo "export PATH=$THEOS/bin:$THEOS/libexec:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV
        ln -s $THEOS/makefiles/common.mk $THEOS/common.mk
        ln -s $THEOS/makefiles/tool.mk $THEOS/tool.mk

    - name: Extract iPhoneOS14.5 SDK
      run: |
        mkdir -p $THEOS/sdks
        tar xJf ./iPhoneOS14.5.sdk.tar.xz -C $THEOS/sdks
        [ -d "$THEOS/sdks/iPhoneOS14.5.sdk" ] || { echo "SDK extraction failed"; exit 1; }

    - name: Build project (修正版)
      run: |
        chmod +x ./ipabuild.sh
        ./ipabuild.sh --signingIdentity="iPhone Distribution: im-wk82"

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Geranium-IPA
        path: packages/*.ipa
