
name: Geranium Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # 指定稳定兼容的macOS 12版本

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup Xcode 14.2
      run: |
        sudo xcode-select -s /Applications/Xcode_14.2.app
        sudo xcodebuild -license accept

    - name: Install dependencies
      run: |
        brew install ldid xz git
        brew install --cask macfuse  # Monterey兼容版本

    - name: Setup Theos
      run: |
        export THEOS=/opt/theos
        sudo mkdir -p $THEOS
        sudo chown -R $USER $THEOS
        git clone --recursive https://github.com/theos/theos.git $THEOS
        echo "THEOS=$THEOS" >> $GITHUB_ENV

    - name: Install SDK
      run: |
        mkdir -p $THEOS/sdks
        curl -L https://github.com/theos/sdks/archive/master.tar.gz | tar xz -C $THEOS/sdks --strip-components=1
        [ -d "$THEOS/sdks/iPhoneOS14.5.sdk" ] || { echo "SDK missing"; exit 1; }

    - name: Build project
      run: |
        chmod +x ./ipabuild.sh
        ./ipabuild.sh

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Geranium-IPA
        path: packages/*.ipa
