
name: Geranium Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Install dependencies
      run: |
        brew install ldid xz git
        brew install --cask macfuse

    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $THEOS
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export THEOS=$HOME/theos" >> $HOME/.bash_profile
        echo "export PATH=$THEOS/bin:$PATH" >> $HOME/.bash_profile

    - name: Download iPhoneOS14.5 SDK
      run: |
        mkdir -p $THEOS/sdks
        curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar xJ -C $THEOS/sdks
        [ -d "$THEOS/sdks/iPhoneOS14.5.sdk" ] || { echo "SDK extraction failed"; exit 1; }

    - name: Build project
      run: |
        chmod +x ./ipabuild.sh
        ./ipabuild.sh

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Geranium-IPA
        path: packages/*.ipa
