name: Build Geranium on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 需要完整克隆历史记录，因为Theos可能需要

    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "$(brew --prefix)/opt/curl/bin" >> $GITHUB_PATH

    - name: Install Theos dependencies
      run: |
        brew install ldid xz git
        brew install --cask osxfuse

    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $THEOS
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export THEOS=$HOME/theos" >> $HOME/.bash_profile
        echo "export PATH=$THEOS/bin:$PATH" >> $HOME/.bash_profile
        source $HOME/.bash_profile

    - name: Install iPhoneOS14.5 SDK
      run: |
        mkdir -p $THEOS/sdks
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mv sdks-master/*.sdk $THEOS/sdks/
        rm -rf master.zip sdks-master
        # 确保iPhoneOS14.5.sdk存在
        if [ ! -d "$THEOS/sdks/iPhoneOS14.5.sdk" ]; then
          echo "iPhoneOS14.5.sdk not found!"
          exit 1
        fi

    - name: Build Geranium
      run: |
        chmod +x ./ipabuild.sh
        ./ipabuild.sh

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Geranium-IPA
        path: packages/*.ipa
