name: Build Geranium (.tipa)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取源码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 安装基础依赖 & 下载预编译 ldid
      - name: Install dependencies and ldid
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

          # 下载预编译 ldid
          # curl -L -o ldid https://github.com/ProcursusTeam/ldid/releases/download/v2.1.2/ldid-x86_64-linux
          mv ldid_linux_x86_64 ldid
          chmod +x ldid
          sudo mv ldid /usr/local/bin/

          sudo apt-get install -y git build-essential clang unzip perl python3 make pkg-config

      # 3️⃣ 设置 Theos
      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin:$PATH" >> $GITHUB_PATH

      # 4️⃣ 解压 iOS SDK
      - name: Extract iOS SDK
        run: |
          mkdir -p $HOME/theos/sdks
          tar -xvf iPhoneOS14.5.sdk.tar.xz -C $HOME/theos/sdks
          ls -la $HOME/theos/sdks

      # 5️⃣ 构建 Geranium
      - name: Build Geranium
        run: |
          chmod +x ./ipabuild.sh
          ./ipabuild.sh
        env:
          THEOS: ${{ env.THEOS }}

      # 6️⃣ 上传构建产物
      - name: Upload .tipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: Geranium-tipa
          path: build/*.tipa
