name: Build Geranium Workflow IPA

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build Geranium
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ldid
        run: brew install ldid
      - name: Build IPA
        run:  ./ipabuild.sh
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: Geranium.tipa
          path: build/Geranium.tipa
